sudo: false
language: elixir
git:
  depth: 3
elixir:
  - 1.3
  - 1.4
otp_release:
  - 18.3
  - 19.3
  - 20.0
env:
  - MIX_ENV=test VERBOSE_TESTS=true
matrix:
  exclude:
    - elixir: 1.3
      otp_release: 20.0
script:
  - mix test --exclude=expensive
  - mix test --only=expensive
notifications:
  email:
    - paulschoenfelder@gmail.com
